version: '3.8'

services:
  # MySQL Database (matching your actual credentials)
  mysql:
    image: mysql:8.0
    container_name: issue-reporting-db
    environment:
      MYSQL_DATABASE: fsdproject
      MYSQL_ROOT_PASSWORD: ""  # Empty password as per your credentials
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"  # Required for empty password
    ports:
      - "3306:3306"  # Changed back to standard port since your app config uses 3306
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root"]
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - issue-reporting-network

  # Spring Boot Application (Backend - issue-reporting folder)
  backend:
    build:
      context: ../issue-reporting  # Pointing to your backend folder
      dockerfile: docker/Dockerfile
    container_name: issue-reporting-backend
    ports:
      - "8081:8081"  # Your backend runs on 8081
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/fsdproject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Empty password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQLDialect
      SERVER_PORT: 8081
      # JWT Configuration
      JWT_SECRET: mySecretKey123456789012345678901234567890123456789012345678901234567890
      JWT_EXPIRATION: 86400000
      # CORS Configuration
      APP_CORS_ALLOWED_ORIGINS: http://localhost:3000
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - app_uploads:/app/uploads
      - ../issue-reporting/logs:/app/logs
    restart: unless-stopped
    networks:
      - issue-reporting-network

  # React Frontend (community-issue-reporting-master folder)
  frontend:
    build:
      context: ../community-issue-reporting-master  # Pointing to your frontend folder
      dockerfile: docker/Dockerfile
    container_name: community-issue-reporting-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:8081  # Points to your backend
    depends_on:
      - backend
    stdin_open: true
    tty: true
    networks:
      - issue-reporting-network

  # phpMyAdmin for database management
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: issue-reporting-phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ""  # Empty password
    ports:
      - "8080:80"  # phpMyAdmin on port 8080
    depends_on:
      - mysql
    networks:
      - issue-reporting-network

volumes:
  mysql_data:
  app_uploads:

networks:
  issue-reporting-network:
    driver: bridge